name: deploy

on:
  workflow_dispatch: {}

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    concurrency: production
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - uses: gacts/fetch-doppler-secret@v1
        id: deploy-token
        with:
          token: ${{ secrets.DOPPLER_NOMAD_PROJECT_TOKEN }}
          project: nomad
          secret-name: ACL_DEPLOY_TOKEN

      - uses: gacts/fetch-doppler-secret@v1
        id: my-tg-id
        with:
          token: ${{ secrets.DOPPLER_TELEGRAM_RSS_BOT_PROJECT_TOKEN }}
          project: telegram-rss-bot
          secret-name: MY_TG_ID

      - uses: gacts/fetch-doppler-secret@v1
        id: bot-token
        with:
          token: ${{ secrets.DOPPLER_TELEGRAM_RSS_BOT_PROJECT_TOKEN }}
          project: telegram-rss-bot
          secret-name: BOT_AUTH_TOKEN

      - uses: gacts/install-nomad@v1

      - run: nomad run -var="telegram_bot_token=${{ steps.bot-token.outputs.secret }}" -var="admin_id=${{ steps.my-tg-id.outputs.secret }}" ./deploy/service.hcl
        env: {NOMAD_ADDR: 'https://nomad.iddqd.uk/', NOMAD_TOKEN: '${{ steps.deploy-token.outputs.secret }}'}
